version: 0.2
phases:
  install:
    commands:
      # Install yarn globally in the codebuild image
      - npm install -g yarn
      # Install required node packages
      - npm install -g serverless
      - yarn install
  build:
    commands:
      # Lint ant compile Typescript
      - yarn run build
      # Run unit tests
      - yarn run test:unit
      # Deploy the serverless stack to 'test' environment for integration tests
      - sls deploy --stage test -v
      # Test lambda functions deployed to 'test' environment
      - yarn run decrypt:test
      - yarn run test:integration
  post_build:
    commands:
      # Remove serverless stack from 'test' environment after integration tests are finished
      - sls remove --stage test -v
