version: 0.2
phases:
  install:
    commands:
      # Setup for Yarn
      - npm install -g yarn
      # Setup OpenJDK in order to start sls offline
      - apt-get update -y && apt-get install openjdk-8-jdk -y
      # Install required node packages
      - npm install -g serverless
      - yarn install
      - sls dynamodb install
  build:
    commands:
      - yarn run build
  post_build:
    commands:
      # Run unit tests
      - yarn run cicd-u-test
      # Run integration tests with sls offline
      - yarn run cicd-decrypt
      - yarn run cicd-i-test