version: 0.2
phases:
  install:
    commands:
      # Install yarn globally in the codebuild image
      - npm install -g yarn
      # Install required node packages
      - npm install -g serverless
      - yarn install
  build:
    commands:
      # Lint ant compile Typescript
      - yarn run build
      # Run unit tests
      - yarn run cicd-u-test
      # Deploy the serverless stack to 'cicd' environment for integration tests
      - sls deploy --stage cicd -v
      # Test lambda functions deployed to 'cicd' environment
      - yarn run cicd-decrypt
      - yarn run cicd-i-test
  post_build:
    commands:
      # Remove serverless stack from 'cicd' environment after integration tests are finished
      - sls remove --stage cicd -v
