# Serverless service
service: whatsmyfit-write # NOTE: update this with your service name

# The provider
provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-2
  environment:
    DYNAMODB_TABLE: notifications-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

# Resources
resources:
  Resources:
    notificationsTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

# Lambda functions
functions:
  notification:
    handler: src/handlers/notifications.create
    events:
      - http:
          path: notifications
          method: post
          documentation:
            summary: Create new Fitbit Notification
            description: Create new Fitbit Notification
            tags:
              - Notifications
            requestBody:
              description: Array of Notifications to create
            requestModels:
              "application/json": NotificationArray
            methodResponses:
              - statusCode: "204"
                responseBody:
                  description: Notifications created

  subscriber:
    handler: src/handlers/subscriber.verify
    environment:
      SUBSCRIBER_VERIFICATION_CODE: ${self:custom.secrets.SUBSCRIBER_VERIFICATION_CODE}
    events:
    - http:
        path: notifications
        method: get
        documentation:
          summary: Verify Fitbit Subscriber
          description: Used by Fitbit Subscriber API to verify Subscriber endpoint
          tags:
            - Notifications
          queryParams:
          - name: verify
            description: The subscriber verification code to be validated
            required: true
          methodResponses:
            - statusCode: "204"
              responseBody:
                description: Subscriber verification code is valid
            - statusCode: "404"
              responseBody:
                description: Subscriber verification code is not valid

# Serverless Plugins
plugins:
  - serverless-aws-documentation
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-secrets-plugin

# Include/Exclude files from package
package:
  exclude:
    - node_modules/**

# API documentation
custom:
  secrets: ${file(secrets.${opt:stage, self:provider.stage}.yml)}
  DB_PREFIX: dev
  dynamodb:
    # If you only want to use DynamoDB Local in some stages, declare them here
    stages:
      - dev
      - cicd
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
    seed:
      domain:
        sources:
          - table: ${self:provider.environment.DYNAMODB_TABLE}
            sources: [./offline/migrations/notifications-seed.json]
  documentation:
    api:
      info:
        version: '2'
        title: WhatsMyFit Write APIs
        description: REST APIs to write data to WhatsMyFit
        contact:
          name: Ismar Slomic
          url: https://whatsmy.fit
          email: ismar@slomic.no
        license:
          name: Licensing
          url: https://whatsmy.fit
    tags:
      - name: Notifications
        description: Api to retrieve new notifications from Fitbit Subscription API
    resources:
      - path: "notifications"
        description: "Fitbit Notifications resource"
    models:
      - name: "Notification"
        description: "Notification to be created"
        contentType: "application/json"
        schema:
          type: "object"
          properties:
            collectionType:
              type: "string"
            date:
              type: "string"
            ownerId:
              type: "string"
            ownerType:
              type: "string"
            subscriptionId:
              type: "string"
      - name: "NotificationArray"
        description: "Array of Notifications to be created"
        contentType: "application/json"
        schema:
          type: "array"
          items:
            $ref: "{{model: Notification}}"